output "network_name" {
  description = "Docker network shared with Compose."
  value       = docker_network.izykube.name
}

output "registry_endpoint" {
  description = "Registry endpoint from the host."
  value       = "http://localhost:${var.registry_port}"
}

output "k3s_api_endpoint" {
  description = "Kubernetes API endpoint from the host."
  value       = "https://127.0.0.1:${var.kubernetes_api_port}"
}

output "kubeconfig_path" {
  description = "Kubeconfig generated by k3s for Terraform addons and kubectl."
  value       = "${local.kubeconfig_directory}/config"
}
