openapi: 3.0.0
info:
  title: Docker image creation API
  version: 1.0.0
paths:
  /create-image:
    post:
      tags:
        - Docker
      summary: Create a new Docker image from a Dockerfile
      parameters:
        - in: query
          name: path
          schema:
            type: string
            description: The path to the Dockerfile on the host system
            example: /path/to/Dockerfile
      responses:
        200:
          description: Image created successfully
          content:
            text/plain:
              schema:
                type: string
                example: sha256:f8c67a3efa3
        400:
          description: Invalid input
        500:
          description: Internal server error
  /authenticate:
    post:
      tags:
        - Authentication
      summary: Creates a new authentication token
      operationId: createAuthenticationToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JwtRequest"
      responses:
        200:
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JwtResponse"
        401:
          description: Invalid credentials
        500:
          description: Internal server error
components:
  schemas:
    JwtRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    JwtResponse:
      type: object
      properties:
        token:
          type: string
        username:
          type: string
        authorities:
          type: array
          items:
            type: object
            properties:
              authority:
                type: string
              role:
                type: string