spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      uri: mongodb://localhost:27017/izykube

server:
  port: 8090
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs

mongock:
  migration-scan-package: com.izylife.izykube.changelogs

app:
  docker:
    local-repository-uri: "localhost:5000"
